/// Bairros de João Pessoa/PB usados no cadastro de chamados.
///
/// Mantemos a lista fora do Widget para respeitar SRP: a tela renderiza o
/// formulário, mas não é dona da fonte de opções de negócio.
const bairrosJoaoPessoa = [
  'Aeroclube',
  'Água Fria',
  'Altiplano Cabo Branco',
  'Alto do Céu',
  'Alto do Mateus',
  'Anatólia',
  'Bancarios',
  'Barra de Gramame',
  'Bessa',
  'Brisamar',
  'Cabo Branco',
  'Castelo Branco',
  'Centro',
  'Cidade dos Colibris',
  'Costa do Sol',
  'Costa e Silva',
  'Cristo Redentor',
  'Cruz das Armas',
  'Cuiá',
  'Distrito Industrial',
  'Ernani Sátiro',
  'Ernesto Geisel',
  'Estados',
  'Expedicionários',
  'Funcionários',
  'Gramame',
  'Grotão',
  'Ilha do Bispo',
  'Indústrias',
  'Ipês',
  'Jaguaribe',
  'Jardim Cidade Universitária',
  'Jardim Oceania',
  'Jardim São Paulo',
  'Jardim Veneza',
  'João Agripino',
  'João Paulo II',
  'José Américo de Almeida',
  'Manaíra',
  'Mandacaru',
  'Mangabeira',
  'Miramar',
  'Muçumagro',
  'Mumbaba',
  'Mussuré',
  'Oitizeiro',
  'Padre Zé',
  'Paratibe',
  'Pedro Gondim',
  'Penha',
  'Planalto Boa Esperanca',
  'Ponta do Seixas',
  'Portal do Sol',
  'Roger',
  'São José',
  'Tambaú',
  'Tambauzinho',
  'Tambiá',
  'Torre',
  'Treze de Maio',
  'Trincheiras',
  'Valentina de Figueiredo',
  'Varadouro',
  'Varjão',
];
